### ISSUE TITLE
Request returns an empty list

### ISSUE THREAD

**Issue by lyubolp** [lyubolp/SPA-Project#22]
**What**: When requesting the `CO` parameter, the parser returns an empty list, regardless of the Station or time
**Where:**: Parser.py -> plot_single_region_day

Run the following code to reproduce it: `plotter.plot_single_region_day(Station.Nadezhda, Parameter.CO, datetime(2017, 5, 21, 0))`

**Comment by luchev** [comment]
The data is incomplete. For the station Nadezhda there is no CO data recorded.
